// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGSTNRrj1zxa9ghBlF4qhDTdD2yFYMq8Q',
    appId: '1:905883475961:web:0867646ecdfd28a6066728',
    messagingSenderId: '905883475961',
    projectId: 'sedal-miracle-49697',
    authDomain: 'sedal-miracle-49697.firebaseapp.com',
    databaseURL: 'https://sedal-miracle-49697-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sedal-miracle-49697.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGCsF9BY1OMe4UYNWH5p73vtvhjjvAy9I',
    appId: '1:905883475961:android:2382cc7c25301665066728',
    messagingSenderId: '905883475961',
    projectId: 'sedal-miracle-49697',
    databaseURL: 'https://sedal-miracle-49697-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sedal-miracle-49697.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9fiDicrOw3ZEt4-lNEcuoNxRHiAKaDaU',
    appId: '1:905883475961:ios:8d05651fc7b9b6eb066728',
    messagingSenderId: '905883475961',
    projectId: 'sedal-miracle-49697',
    databaseURL: 'https://sedal-miracle-49697-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sedal-miracle-49697.firebasestorage.app',
    iosBundleId: 'com.sedalmiracle.sedalMiracle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9fiDicrOw3ZEt4-lNEcuoNxRHiAKaDaU',
    appId: '1:905883475961:ios:8d05651fc7b9b6eb066728',
    messagingSenderId: '905883475961',
    projectId: 'sedal-miracle-49697',
    databaseURL: 'https://sedal-miracle-49697-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sedal-miracle-49697.firebasestorage.app',
    iosBundleId: 'com.sedalmiracle.sedalMiracle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGSTNRrj1zxa9ghBlF4qhDTdD2yFYMq8Q',
    appId: '1:905883475961:web:ce618446944a2e38066728',
    messagingSenderId: '905883475961',
    projectId: 'sedal-miracle-49697',
    authDomain: 'sedal-miracle-49697.firebaseapp.com',
    databaseURL: 'https://sedal-miracle-49697-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sedal-miracle-49697.firebasestorage.app',
  );
}
